config/routes.rb
RealtimeProject1::Application.routes.draw do

  
  devise_for :users
  resources :movies, :theatres, :timings do
    collection do
      get :search
    end
  end
 

  
  

    
 

end

app/models/movie.rb
class Movie < ActiveRecord::Base
	has_many :theatres
	belongs_to :theatre

	before_validation :display_msg
	after_validation :show_msg

	#before_save :capitalize_first_letter
	before_save do |t|
		t.name = t.name.upcase.titleize
		t.actor = t.actor.upcase.titleize
		t.actress = t.actress.upcase.titleize
	end




	validates_presence_of :name, :actor, :actress, :message => ": cant be blank"
	validates_length_of :name, :actor, :actress, :in => 2..20, :message => ": should have minimum 2 and maximum 20 letters"
	validates_format_of :actor, :actress, :with =>  /\A[a-zA-Z\s]+\Z/, :excluded_chars => %w('then', 'an'), :message => ": only alphabets"
	validates_format_of :name, :with =>  /\A[a-zA-Z0-9\s]+\z/, :message => ": only alphanumerics"

	def self.search(query)
		if query
			where(['name LIKE ? OR actor LIKE ? OR actress LIKE ?', "#{query}%", "#{query}%", "#{query}%"])
		else
			scoped
		end
	end

	private
	def show_msg
		puts "validation completed"
	end

	def display_msg

		puts "validation started"
	end

	

	#private
	#def capitalize_first_letter
	#	self.name = self.name.upcase
	#	self.actor = self.actor.upcase.titleize
	#	self.actress = self.actress.upcase.titleize
		#new_string = string.slice(0,1).capitalize + string.slice(1..-1)
	#end




end

app/models/theatre.rb
class Theatre < ActiveRecord::Base
	has_many :movies
	has_many :timings
	belongs_to :movie
	before_save :capitalize_first_letter
	after_validation :show_msg


	validates_presence_of :theatre_name, :place, :time, :message => ": cant be blank"
	validates_length_of :theatre_name, :place, :time, :in => 2..20, :message => ": should have minimum 2 and maximum 20 letters"
	validates_format_of :theatre_name, :place, :time, :with =>  /\A[a-zA-Z0-9\s]+\z/, :excluded_chars => %w('then', 'an'), :message => ": only alphanumerics"


	def self.search(search)
		if search
			find(:all, :conditions => ['theatre_name LIKE ? OR place LIKE ? OR time LIKE ?', "#{search}%", "#{search}%", "#{search}%"])

		else
			find(:all)
		end
	end

	private
	def capitalize_first_letter
		self.theatre_name = self.theatre_name.upcase
		self.place = self.place.upcase.titleize
		self.time = self.time.upcase.titleize
	end

	def show_msg
		if Theatre.new.errors.any? 
			puts "invalid input"
		else
			puts "no errors"
		end
	end

end

app/models/timing.rb
class Timing < ActiveRecord::Base
	belongs_to :theatre

	before_save :capitalize_first_letter
	
	

	validates_presence_of :morning_show, :matinee_show, :first_show, :second_show, :message => ": cant be blank"
	validates_length_of  :morning_show, :matinee_show, :first_show, :second_show, :in => 2..20, :message => ": should have minimum 2 and maximum 20 letters"
	validates_format_of  :morning_show, :matinee_show, :first_show, :second_show, :with =>  /\A[a-zA-Z0-9\s]+\z/, :excluded_chars => %w('then', 'an'), :message => ": only alphanumerics"


	def self.search(search)
		if search
			find(:all, :order => 'theatre_name', :conditions => ['theatre_name LIKE ?', "#{search}%"])
			
		else
			find(:all)
		end
	end

	private
	def capitalize_first_letter
		
		self.morning_show = self.morning_show.upcase.titleize
		self.matinee_show = self.matinee_show.upcase.titleize
		self.first_show = self.first_show.upcase.titleize
		self.second_show = self.second_show.upcase.titleize
	end

	

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!



end

app/controllers/movies_controller.rb
  class MoviesController < ApplicationController

    before_action :set_movie, only: [:show, :edit, :update, :destroy]
    before_filter :allow_iframe_requests


    def allow_iframe_requests
      response.headers.delete('X-Frame-Options')
    end


    def index
     @movies = Movie.all
     @theatres = Theatre.all
     @timings = Timing.all

   end

   def show
   end

   def new
    @movie = Movie.new
   end

   def create
     @movie = Movie.new(movie_params)
     if @movie.save
       redirect_to movies_path
     end
   end

  def edit
  end

  def update
   if @movie.update_attributes(movie_params)
    redirect_to movies_path
  end	
end

def destroy
  if @movie.destroy
    redirect_to movies_path
  end
end





def set_movie
 @movie = Movie.find(params[:id])
end

def movie_params
 params.require(:movie).permit(:name, :actor, :actress, :theatre_id)
end

def search
 @search = Movie.search(params[:search])
 if @search == []
  @search1 = 'No record found'
end
end





#def next

 # 	user = Account.find_by(username: params[:account][:username], password: params[:account][:password])

    #@user3 = Account.select("username, password").where(username: params[:username], password: params[:login][:password])

  #	if user == nil
	#	@print = 'Invalid login: Please check your username and password'
#	else
#		@print = 'Login successful!!'
#	end



end

app/controllers/theatres_controller.rb
class TheatresController < ApplicationController
  before_action :set_theatre, only: [:show, :edit, :update, :destroy]

  def index
     @movies = Movie.all
     @theatres = Theatre.all
     @timings = Timing.all
  end

  def new
    @theatre = Theatre.new
  end

  def create
    @theatre = Theatre.new(theatre_params)
    if @theatre.save
      redirect_to theatres_path
    end
  end

  def show
  end

  def edit
  end
  
  def update
   if @theatre.update(theatre_params)
    redirect_to theatres_path
  end 
  end 

  def destroy
    if @theatre.destroy
      redirect_to theatres_path
    end
  end

  def theatre_params
     params.require(:theatre).permit(:theatre_name, :place, :time)
  end

  def search
     @search = Theatre.search(params[:search])
      if @search == []
      @search1 = 'No record found'
      end
  end

  def set_theatre
  @theatre = Theatre.find(params[:id])
  end
end

app/controllers/timings_controller.rb
class TimingsController < ApplicationController
  before_action :set_timing, only: [:show, :edit, :update, :destroy]

  def index
   @movies = Movie.all
   @theatres = Theatre.all
   @timings = Timing.all
  end

  def new
  @timing = Timing.new
  end

  def create
  @timing = Timing.new(timing_params)
  if @timing.save
    redirect_to timings_path
  end
  end

  def show
  end

  def edit
  end

  def update
   if @timing.update(timing_params)
    redirect_to timings_path
  end
  end

  def destroy
    if @timing.destroy
      redirect_to timings_path
    end
  end

  def search
    @search = Timing.search(params[:search])
    if @search == []
      @search1 = 'No record found'
    end
  end

  private

  def timing_params
   params.require(:timing).permit(:morning_show, :matinee_show, :first_show, :second_show, :theatre_id)
  end

 def set_timing
  @timing = Timing.find(params[:id])
 end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper

end

app/helpers/theatres_helper.rb
module TheatresHelper
	
end

app/helpers/timings_helper.rb
module TimingsHelper
	
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Movies | <%= yield(:title) %></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>

  <!-- user defined -->
  <style>
    body 
    {
      background: linear-gradient(white, #b0c4de); 
      color:black;
      font-family: verdana;

    }

    #grad1
    {
      height:1000px;
      width:1200px;
      float:right;
      margin-top:130px;


    }

    p.ex 
    {
      color:red;
      position:fixed;
      right:50px;
      top:20px;

    }

    p.one
    {
      border-style:solid;
      border-color:yellow;
    }
    div.fixed1
    {
      position: fixed;
      right:40px;
      left:0px;
    }
    div.fixed
    {
      position:fixed;
      top:90px;
      left:0px; 
    }

    p.imge
    {
      background:url("/reel3.jpg");
      background-size:200px 150px;
      background-repeat:no-repeat;
      background-position: 600px 150px;
      padding-top:40px;
    }
    div.transbox
    {
      position: fixed;
      top: 120px;
      left: 200px;
      float: right;
      width: 360px;
      height: 400px;
      margin: 30px 50px;
      background-color: #ffffff;
      border: 1px solid black;
      opacity:0.7;
    }
    div.transbox2
    {
      position: fixed;
      top: 240px;
      left: 650px;
      float: right;
      width: 300px;
      height: 200px;
      margin: 30px 50px;
      background-color: #ffffff;
      border: 1px solid black;
      opacity:0.7;
    }
    div.transbox p
    {
      margin: 30px 40px;
      font-weight: bold;
      color: #000000;
    }
    #frame1
    {
      position:fixed;
      top: 240px;
      left: 650px;
      float: right;
      width: 500px;
      height: 300px;
      margin: 30px 50px;
      border: 1px solid black;
      opacity: .5;
    }


  </style>



</head>


<body>

  <div id="container" style="width:1500px">


    <div class="fixed1" style="background-color:#b0c4de;height:90px;width:1450px;">
      <p class="navbar-text pull-right">
        <% if user_signed_in? %>
          Logged in as <strong><%= current_user.email %></strong>.

          <%= link_to 'Edit Profile', edit_user_registration_path, :class => 'navbar-link' %> |
          <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
          <% else %>
          <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
          <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
        <% end %>


        <!--login authentication-->
        <% if notice %>
        <p class="alert alert-notice"><%= notice %></p>
        <% end %>
        <% if alert %>
        <p class="alert alert-error"><%= alert %></p>
        <% end %>


        <h1 style="color:maroon;"><center>My Movies</center></h1>
        <p class="ex"></br>| <%= link_to 'Movies', movies_path %> |<%= link_to 'Theatres', theatres_path %> |<%= link_to 'Timings', timings_path %> |</br></p>
    </div>

    <div class="fixed" id="menu" style="background: linear-gradient(#F5DEB3, white);height:1000px;width:200px;">
       <p><h4 style="color:green"><u>List of Movies:</u></h4></p>
       <ol>
        <li><%= link_to 'One', '/movies/4' %></li>
        <li><%= link_to 'AD', '/movies/1' %></li>
        <li><%= link_to 'SVSC', '/movies/2' %></li>
        <li><%= link_to 'Yevadu', '/movies/3' %></li>
        <li><%= link_to 'Laddu Babu', '/movies/5' %></li>
        
      </ol> 
      <p><h4 style="color:green"><u>List of Theatres:</u></h4></p>
      <ol>
        <li><%= link_to 'Aradhana', '/timings/1' %></li>
        <li><%= link_to 'Srinivasa-Uppal', '/timings/2' %></li>
        <li><%= link_to 'Sandhya', '/timings/3' %></li>
        <li><%= link_to 'Sudarshan', '/timings/4' %></li>
        <li><%= link_to 'Shanthi', '/timings/5' %></li>
        <li><%= link_to 'Sri Krishna', '/timings/6' %></li>
        <li><%= link_to 'Raj Lakshmi', '/timings/7' %></li>
        <li><%= link_to 'Srinivasa-Tarnaka', '/timings/8' %></li>
      </ol> </br>

    </div>
   
  

    <div id="grad1" class="transbox1">


      <%= yield %>
    </div>
  </div>





  </body>
  </html>

app/views/movies/_movie.html.erb
<li><%= movie.name %></li>

app/views/movies/create.html.erb
<% if @movie.errors.any? %>
  <div id="error_explanation" style="color:red">
    <h2><%= pluralize(@movie.errors.count, "error") %> prohibited this post from being saved:</h2>
 
    <ol>
    <% @movie.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ol>
  
  </div>

<%= form_for @movie do |f| %>
  <%= f.label :name %></br>
  <%= f.text_field :name %></br></br>
  <%= f.label :actor %></br>
  <%= f.text_field :actor %></br>
  <%= f.label :actress %></br>
  <%= f.text_field :actress %></br> 
  <%= f.submit %>

<% end %>
<% end %>

app/views/movies/edit_movie.html.erb
<%= form_for @movie do |f| %>
	<%= f.label :name %></br>
	<%= f.text_field :name %></br></br>
	<%= f.label :actor %></br>
	<%= f.text_field :actor %></br>
	<%= f.label :actress %></br>
	<%= f.text_field :actress %></br>	
	<%= f.submit %>

<% end %>

app/views/movies/edit_theatre.html.erb
<%= form_for @theatre do |f| %>

	<%= f.label :theatre_name %></br>
	<%= f.text_field :theatre_name %></br></br>
	<%= f.label :place %></br>
	<%= f.text_field :place %></br>
	<%= f.label :time %></br>
	<%= f.text_field :time %></br>	
	<%= f.submit %>

<% end %>

app/views/movies/index.html.erb
<% provide(:title, 'Home') %>
</br></br> 
Search movies by name/actor/actress
<%= form_tag search_movies_path, method: :get do %>
<p>
	<%= text_field_tag :search, params[:search], size: 35, placeholder: "you can use movie/actor/actress names" %> 
	<%= submit_tag "Search Movies", :name => nil  %>
</p>
<% end %>



</br></br>

<h2>Movies</h2><%= link_to '(Create new)', new_movie_path %>
<table class="table table-striped">
	<thead>
		<tr>
			<th>Movie Name </th>
			<th>Actor </th>
			<th>Actress</th>
			<th>Show movie</th>
			<th>Edit movie</th>
			<th>Delete movie</th>

		</tr>
	</thead>
	<tbody>
		
		<% @movies.each do |f| %>
		<tr>
			<td><%= f.name %></td>
			<td><%= f.actor %></td>
			<td><%= f.actress %></td>
			<td><%= link_to ' Show  ', movie_path(f) %></td>
			<td><%= link_to ' Edit ', edit_movie_path(f) %></td>
			<td><%= link_to 'Destroy', f, method: :delete, data: { confirm: 'Are you sure?' } %></td>
		</tr>
		<% end %>
	</tbody>
</table>

app/views/movies/movie_show.html.erb
<p> Movie Name: <%= @movie.name %> </p>
<p> Actor : <%= @movie.actor %> </p>
<p> Actress : <%= @movie.actress %> </p>

<p> Theatre Name: <%= @movie.theatre.theatre_name %> </p>
<p> Show time: <%= @movie.theatre.time %> </p>
<p> Location:  <%= @movie.theatre.place %> </p>








<%= link_to 'Home', home_path %>

app/views/movies/new.html.erb
<% provide(:title, 'New') %>
		
<%= form_for @movie do |f| %>
	<%= f.label :name %></br>
	<%= f.text_field :name %></br></br>
	<%= f.label :actor %></br>
	<%= f.text_field :actor %></br>
	<%= f.label :actress %></br>
	<%= f.text_field :actress %></br>	
	<%= f.submit %>

<% end %>

app/views/movies/search.html.erb
<% provide(:title, 'Search') %>
</br></br>
<h3 style="color:green">Here is what we found for you:</br></br></h3>


 <h4 style="color:blue">Your quey has yielded <%= pluralize(@search.count, "result") %>. </h4>

<p class="one"><h5 style="color:purple"><ol><% @search.each do |f| %>
<li>Movie name :<%= f.name %></br>
Actor :<%= f.actor %></br>
Actress :<%= f.actress%></li></br>
<% end %></ol>
<%= @search1 %></h5></p>




	<%= link_to 'Home', movies_path %>

app/views/movies/search_timing.html.erb
</br></br>
<h3 style="color:green">Here is what we found for you:</br></br></h3>



  <h4 style="color:blue">Your quey has yielded <%= pluralize(@search.count, "result") %>. </h2>


 <p class="one"><h5 style="color:purple"><ol><%  @search.each do |f| %>
        					<li> Theatre Name :<%= f.theatre_name %></br>
        						Morning show :<%= f.morning_show %></br>
        							Matinee show :<%= f.matinee_show %></br>
        					    First show :<%= f.first_show %></br>
        						Second show :<%= f.second_show%> </li></br>
        						<% end %></ol>
   		<%= @search1 %>
   	    </h5></p>
   
    
    

app/views/movies/show.html.erb
<% provide(:title, 'Show') %>
<div class="transbox">
<p> Movie Name: <%= @movie.name %> </p>
<p> Actor : <%= @movie.actor %> </p>
<p> Actress : <%= @movie.actress %> </p>

<p> Theatre Name: <%= @movie.theatre.theatre_name %> </p>
<p> Show time: <%= @movie.theatre.time %> </p>
<p> Location:  <%= @movie.theatre.place %> </p>




&nbsp&nbsp&nbsp<%= link_to 'Home', movies_path %>

</div>
 <iframe id="frame1" name="iframe_2" style="position:absolute;top: 100px;left: 700px;float: right;width: 600px;height: 400px;margin: 30px 50px;border: 1px solid black;opacity: 1;"></iframe>


<% if @movie.id == 1 %> 
	<%= link_to 'view review here', "http://entertainment.oneindia.in/telugu/movies/attharintiki-daaredhi/review.html" , { :target => "iframe_2" } %>

<% elsif @movie.id == 2 %>
	<%= link_to 'view review here', "http://entertainment.oneindia.in/telugu/movies/seethamma-vakitlo-sirimalle-chettu/review.html" , { :target => "iframe_2" } %>

<% elsif @movie.id == 5 %>
	<%= link_to 'view review here', "http://entertainment.oneindia.in/telugu/movies/laddu-babu/review.html" , { :target => "iframe_2" } %>

<% elsif @movie.id == 4 %>
	<%= link_to 'view review here', "http://entertainment.oneindia.in/telugu/movies/1-nenokkadine/review.html" , { :target => "iframe_2" } %>

<% elsif @movie.id == 3 %>
	<%= link_to 'view review here', "http://entertainment.oneindia.in/telugu/movies/yevadu/review.html" , { :target => "iframe_2" } %>
<% end %>

	

  
    

app/views/movies/show_movie.html.erb
<p> Movie Name: <%= @movie.name %> </p>
<p> Actor : <%= @movie.actor %> </p>
<p> Actress : <%= @movie.actress %> </p>

<p> Theatre Name: <%= @movie.theatre.theatre_name %> </p>
<p> Show time: <%= @movie.theatre.time %> </p>
<p> Location:  <%= @movie.theatre.place %> </p>








<%= link_to 'Home', home_path %>

app/views/movies/show_theatre.html.erb
<p> Theatre Name: <%= @theatre.theatre_name %> </p>
<p> Show time: <%= @theatre.time %> </p>
<p> Location:  <%= @theatre.place %> </p>
 



<p> Movie Name: <%= @theatre.movie.name %> </p>
<p> Actor : <%= @theatre.movie.actor %> </p>
<p> Actress : <%= @theatre.movie.actress %> </p>









<%= link_to 'Home', home_path %>

app/views/movies/show_timing.html.erb
<p> Theatre Name: <%= @timing.theatre.theatre_name %> </p>
<p> Show timings: <%= @timing.theatre.time %> </p>
<p> Location:  <%= @timing.theatre.place %> </p>
 


<p> Morning show: <%= @timing.morning_show %> </p>
<p> Matinee show: <%= @timing.matinee_show %> </p>
<p> First show:  <%= @timing.first_show %> </p>
<p> Second show:  <%= @timing.second_show %> </p>
 
 

</br></br>







<%= link_to 'Home', home_path %>

app/views/movies/theatre_show.html.erb
<p> Theatre Name: <%= @theatre.theatre_name %> </p>
<p> Show time: <%= @theatre.time %> </p>
<p> Location:  <%= @theatre.place %> </p>
 
<p> Movie Name: <%= @theatre.movie.name %> </p>
<p> Actor : <%= @theatre.movie.actor %> </p>
<p> Actress : <%= @theatre.movie.actress %> </p>









<%= link_to 'Home', home_path %>

app/views/theatres/create.html.erb
<% if @theatre.errors.any? %>
  <div id="error_explanation" style="color:red">
    <h2><%= pluralize(@theatre.errors.count, "error") %> prohibited this post from being saved:</h2>
 
    <ol>
    <% @theatre.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ol>
  </div>
  
  
<% end %>



		

app/views/theatres/edit.html.erb
<% provide(:title, 'Theatre - Edit') %>

<%= form_for @theatre do |f| %>

	<%= f.label :theatre_name %></br>
	<%= f.text_field :theatre_name %></br></br>
	<%= f.label :place %></br>
	<%= f.text_field :place %></br>
	<%= f.label :time %></br>
	<%= f.text_field :time %></br>	
	<%= f.submit %>

<% end %>

app/views/theatres/index.html.erb
<% provide(:title, 'Theatres - Home') %>
</br></br>



Search theatre by name/location
<%= form_tag search_theatres_path, method: :get do %>
  <p>
    <%= text_field_tag :search, params[:search], size: 35, placeholder: "you can enter theatre name/location" %>
    <%= submit_tag "Search Theatres", :name => nil %>
  </p>
<% end %>



</br></br>

<h2>Theatres</h2><%= link_to '(Create new)', new_theatre_path %>
<table class="table table-bordered">
	<thead>
		<tr>
			<th>Theatre Name </th>
			<th>Place </th>
			<th>Time</th>
			<th>Movie Id</th>
			<th>Show Details</th>
			<th>Edit Details</th>
			<th>Delete </th>
		</tr>
	</thead>
	<tbody>
		<% @theatres.each do |f| %>
			<tr>
				<td><%= f.theatre_name %></td>
				<td><%= f.place %></td>
				<td><%= f.time %></td>
				<td><%= f.movie_id%></td>
				<td><%= link_to ' Show  ', theatre_path(f) %></td>
				<td><%= link_to ' Edit ', edit_theatre_path(f) %></td>
				<td><%= link_to ' Destroy ', f, method: :delete, data: {confirm: "Are you sure?"} %></td>
			</tr>
		<% end %>
	</tbody>
</table> 

</br></br>

app/views/theatres/new.html.erb
<% provide(:title, 'Theatre - New') %>

<%= form_for @theatre do |f| %>

	<%= f.label :theatre_name %></br>
	<%= f.text_field :theatre_name %></br></br>
	<%= f.label :place %></br>
	<%= f.text_field :place %></br>
	<%= f.label :time %></br>
	<%= f.text_field :time %></br>	
	<%= f.submit %>

<% end %>

app/views/theatres/search.html.erb
<% provide(:title, 'Theatre - Search') %>
</br></br>
<h3 style="color:green">Here is what we found for you:</br></br></h3>

      
 <h4 style="color:blue">Your quey has yielded <%= pluralize(@search.count, "result") %>. </h4>

 <p class="one"><h5 style="color:purple"><ol>
       <%  @search.each do |f| %>
        <li>Theatre Name :<%= f.theatre_name %></br>
        Location :		<%= f.place %></br>
        show timings:	<%= f.time %></li></br>
        <% end %></ol>
   		
   	 

   	    <%= @search1 %> </h5></p>   
   
    
    


<%= link_to 'Home', theatres_path %>

app/views/theatres/show.html.erb
<% provide(:title, 'Theatre - Show') %>
<div class="transbox">
<p> Theatre Name: <%= @theatre.theatre_name %> </p>
<p> Show time: <%= @theatre.time %> </p>
<p> Location:  <%= @theatre.place %> </p>
 



<p> Movie Name: <%= @theatre.movie.name %> </p>
<p> Actor : <%= @theatre.movie.actor %> </p>
<p> Actress : <%= @theatre.movie.actress %> </p>









&nbsp&nbsp&nbsp<%= link_to 'Home', theatres_path %>
</div>

app/views/theatres/update.html.erb
<% if @theatre.errors.any? %>
  <div id="error_explanation" style="color:red">
    <h2><%= pluralize(@theatre.errors.count, "error") %> prohibited this post from being saved:</h2>
 
    <ol>
    <% @theatre.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ol>
  </div>
  
<% end %>

		

app/views/timings/create.html.erb
<% if @timing.errors.any? %>
  <div id="error_explanation" style="color:red">
    <h2><%= pluralize(@timing.errors.count, "error") %> prohibited this post from being saved:</h2>
 
    <ol>
    <% @timing.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ol>
  </div>
  
<% end %>

		

app/views/timings/edit.html.erb
<% provide(:title, 'Show Time - Edit') %>

<%= form_for @timing do |f| %>

	<%= f.label :theatre_name %></br>
	<%= f.text_field :theatre_name %></br></br>
	<%= f.label :morning_show %></br>
	<%= f.text_field :morning_show %></br>
	<%= f.label :matinee_show %></br>
	<%= f.text_field :matinee_show %></br>	
	<%= f.label :first_show %></br>
	<%= f.text_field :first_show %></br>	
	<%= f.label :second_show %></br>
	<%= f.text_field :second_show %></br>	
	<%= f.label :theatre_id %></br>
	<%= f.text_field :theatre_id %></br>	
	<%= f.submit %>

<% end %>

 

app/views/timings/index.html.erb
<% provide(:title, 'Show Time - Home') %>
</br></br>


Search theatre-timings and shows
<%= form_tag search_timings_path, method: :get do %>
  <p>
    <%= text_field_tag :search, params[:search], size: 35, placeholder: "Enter any theatre name" %>
    <%= submit_tag "Search Timings", :name => nil %>
  </p>
<% end %></br></br>


<h2>Timings</h2><%= link_to '(Create new)', new_timing_path %>
<table class="table table-hover">
	<thead>
		<tr>
			
			<th>Theatre id</th>
			<th>Theatre name</th>
			<th>Show Details</th>
			<th>Edit Details</th>
			<th>Delete</th>
		</tr>
	</thead>
	<tbody>
		<% @timings.each do |f| %>
			<tr>
			
			    <th><%= f.theatre_id %></th>
			    <th><%= f.theatre_name %></th>
				<td><%= link_to ' Show  ', timing_path(f) %></td>
				<td><%= link_to ' Edit ', edit_timing_path(f) %></td>
				<td><%= link_to ' Destroy ', f, method: :delete, data: {confirm: "Are you sure?"} %></td>
			</tr>
		<% end %>
	</tbody>
</table>

</br></br></br>

app/views/timings/new.html.erb
<% provide(:title, 'Show Time - New') %>

<%= form_for @timing do |f| %>

	<%= f.label :theatre_name %></br>
	<%= f.text_field :theatre_name %></br></br>
	<%= f.label :morning_show %></br>
	<%= f.text_field :morning_show %></br>
	<%= f.label :matinee_show %></br>
	<%= f.text_field :matinee_show %></br>	
	<%= f.label :first_show %></br>
	<%= f.text_field :first_show %></br>	
	<%= f.label :second_show %></br>
	<%= f.text_field :second_show %></br>	
	<%= f.label :theatre_id %></br>
	<%= f.text_field :theatre_id %></br>	
	<%= f.submit %>

<% end %>

 